class Config:
    SECONDS_ADDED_TO_EVENT_TIMESTAMP = 5
    FRAME_DELIMITER_FOR_REZ_NET_TENSORFLOW = 20
    FRAME_DELIMITER_FOR_SSD_TENSORFLOW = 5
    CAMERA_IP_ADDRESS = 'IP PLACEHOLDER'
    CAMERA_PORT = 'IP PORT PLACEHOLDER'
    CAMERA_USERNAME = 'CAMERA USERNAME PLACEHOLDER'
    CAMERA_PASSWORD = 'CAMERA PASSWORD'

    WINDOW_TITLE_FONT_SIZE = 16
    READER_REVIEWER_WINDOW_WIDTH = 2300
    READER_REVIEWER_WINDOW_HEIGHT = 1380
    DETECTION_REVIEWER_WINDOW_WIDTH = 1080
    DETECTION_REVIEWER_WINDOW_HEIGHT = 1920
    MAIN_MENU_WINDOW_WIDTH = 720
    MAIN_MENU_WINDOW_HEIGHT = 720
    TRAINER_WINDOW_HEIGHT = 1350
    TRAINER_WINDOW_WIDTH = 1350
    DATABASE_USERNAME = 'DATABASE USER NAME PLACEHOLDER'
    DATABASE_PASSWORD = 'DATABASE PASSWORD PLACEHOLDER'
    DATABASE_NAME = 'DATABASE NAME PLACEHOLDER'
    DATABASE_HOST = 'DATABASE HOST PLACEHOLDER'
    THREAD_LOOP_DELAY = .1
    VALID_VIDEO_FORMATS = ['.mp4']

    # file extensions
    INFERENCE_GRAPH_FILE_EXTENSION = '.pb'
    OBJECT_LABELS_FILE_EXTENSION = '.pbtxt'
    VALID_IMAGE_DATA_SET_EXTENSIONS = ['xml', 'jpg']
    INVALID_IMAGE_FORMATS = ['png', 'jpeg', 'gif', 'TIF']

    # live stream_recordings
    SECONDS_PER_RECORDING = 20
    RECORDINGS_FORMAT = '.mp4'

    MINIMUM_NUMBER_OF_IMAGES = 200
    DEFAULT_TEST_PERCENTAGE = 10
    MAXIMUM_IMAGE_SIZE_IN_MEGABYTES = .6

    # models
    TENSOR_FLOW_OBJECT_DETECTION_DIRECTORY = \
        'PATH TO TENSORFLOW OBJECT DETECTION API PLACEHOLDER ' \
        '/Tensorflow_Object_Detection_API/models/research/object_detection/'
    TENSOR_FLOW_PYTHON_PATH = 'export PYTHONPATH=$PYTHONPATH:' \
                              'PATH TO TENSORFLOW OBJECT DETECTION API PLACEHOLDER' \
                              '/Tensorflow_Object_Detection_API/models/research:' \
                              'PATH TO TENSORFLOW OBJECT DETECTION API PLACEHOLDER' \
                              '/Tensorflow_Object_Detection_API/models/research/slim '
